--创建健康视图
--方便查看
CREATE OR REPLACE VIEW health_view as
(
--查询出相对应的用户名、动物名一起显示出来
SELECT ANIMAL.ANIMAL_ID,ANIMAL.ANIMAL_NAME,USER_INFORMATION.USER_ID,USER_INFORMATION.USER_NAME,
      HEALTH_CHECK_INFORMATION.HEALTH_INFORMATION,TO_CHAR(HEALTH_CHECK_INFORMATION.CHECK_DATE,'YYYY-MM-DD')CHECK_DATE,HEALTH_CHECK_INFORMATION.REMARKS

FROM ANIMAL,USER_INFORMATION,HEALTH_CHECK_INFORMATION
WHERE HEALTH_CHECK_INFORMATION.USER_ID = USER_INFORMATION.USER_ID AND
      HEALTH_CHECK_INFORMATION.ANIMAL_ID = ANIMAL.ANIMAL_ID
)
