--创建用户视图
--方便查看
CREATE OR REPLACE VIEW User_View
AS
(
SELECT USER_ID,USER_NAME,EMAIL,CELLPHONE_NUMBER,USER_INFORMATION.SHELTER_ID,SHELTER_NAME
FROM USER_INFORMATION,SHELTER
WHERE USER_INFORMATION.SHELTER_ID = SHELTER.SHELTER_ID
)
