
--建立视图VACCINE_RECORD_VIEW
--方便查看信息
CREATE OR REPLACE VIEW VACCINE_RECORD_VIEW (USER_ID, USER_NAME,VACCINE_ID,vaccine_name,ANIMAL_ID ,animal_name,Vaccination_time,Remarks)
as
(
--查询出相对应的用户名等方便查询
select VACCINE_RECORD.USER_ID,USER_NAME,VACCINE_RECORD.VACCINE_ID,VACCINE.vaccine_name,VACCINE_RECORD.ANIMAL_ID, animal_name，TO_CHAR(Vaccination_time,'YYYY-MM-DD') Vaccination_time，Remarks
from VACCINE_RECORD,VACCINE,USER_INFORMATION,ANIMAL
WHERE VACCINE_RECORD.VACCINE_ID = VACCINE.VACCINE_ID AND
      VACCINE_RECORD.ANIMAL_ID =ANIMAL.ANIMAL_ID AND
      VACCINE_RECORD.USER_ID = USER_INFORMATION.USER_ID
)
